import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

// Import global layout components (Header and Footer)
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";

// Configure local fonts (Geist Sans and Geist Mono) for the application
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define global metadata for SEO and browser tab title/description
export const metadata: Metadata = {
  title: "Adil Store",
  description: "E-commerce platform generated by Adil",
};

// Import providers and UI components
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import { StoreProvider } from "@/context/StoreContext";

// RootLayout is the main wrapper for all pages in the application
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* StoreProvider handles global state management for the store */}
        <StoreProvider>
          {/* ThemeProvider handles Light/Dark mode switching */}
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* The Navbar will appear on every page */}
            <Navbar />
            
            {/* Render the specific page content */}
            {children}
            
            {/* The Footer will appear on every page */}
            <Footer />
            
            {/* Toaster is used to display popup notifications (toast messages) */}
            <Toaster />
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
